version: "3"

services:
  trwip:
    image: gabrielsclimaco/trwip:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.production
    links:
      - rethink
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - static:/web/frontend/dist
      - uploads:/web/uploads
      - nginx_etc:/etc/nginx
    environment:
      - DB_HOST=rethink
      - WEB_HOST=http://nginx
      - NODE_ENV=production
    depends_on:
      - rethink
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - trwip
    volumes:
      - nginx_etc:/etc/nginx
      - static:/web/frontend/dist
      - uploads:/web/uploads
    ports:
      - "80:80"
    depends_on:
      - trwip
  rethink:
    image: rethinkdb:latest
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - db:/data
volumes:
  static: {}
  uploads: {}
  db: {}
  nginx_etc: {}
