// user
export const STORE_TOKEN = 'storeToken'
export const LOGOUT = 'logout'
export const LOGIN = 'login'
export const CHECK_IF_LOGGED = 'checkIfLogged'
export const REGISTER = 'register'
export const RETRIEVE_USER = 'retrieveUser'
export const UPDATE_USER = 'updateUser'
export const FETCH_CURRENT_USER = 'fetchCurrentUser'
export const FETCH_USERS = 'fetchUsers'
export const EVALUATE_USER = 'evaluateUser'

// trwip
export const CREATE_TRWIP = 'createTrwip'
export const FETCH_TRWIP_SLICE = 'fetchTrwipsSlice'
export const CLEAN_SEARCH = 'cleanSearch'
export const RETRIEVE_TRWIPS = 'retrieveTrwips'
export const RETRIEVE_TRWIP = 'retrieveTrwip'
export const UPSERT_TRWIP = 'upsertTrwip'
export const JOIN_TRWIP = 'joinTrwip'
export const LEAVE_TRWIP = 'leaveTrwip'
export const CONFIRM_JOIN_TRWIP = 'confirmJoinTrwip'
export const UNCONFIRM_JOIN_TRWIP = 'unconfirmJoinTrwip'
export const CONFIRM_INVITE_TRWIP = 'confirmInviteTrwip'
export const UNCONFIRM_INVITE_TRWIP = 'unconfirmInviteTrwip'
export const USER_TRWIP = 'userTrwip'
export const SEND_EMAIL_INVITES = 'sendEmailInvites'
export const SEND_MANY_INVITES = 'sendManyInvites'
export const SEND_INVITE = 'sendInvite'
export const EVALUATE = 'evaluate'
export const DELETE_TRWIP = 'deleteTrwip'

// channel
export const CREATE_CHANNEL = 'createChannel'
export const FETCH_CURRENT_CHANNEL = 'fetchCurrentChannel'
export const FETCH_CHANNELS_COUNT = 'fetchChannelsCount'
export const VERIFY_PERSONAL_CHAT = 'verifyPersonalChat'
export const JOIN_CHANNELS = 'joinChannels'
export const READ_MESSAGES = 'readMessages'

// notification
export const READ_NOTIFICATIONS = 'readNotifications'
export const FETCH_NOTIFICATIONS = 'fetchNotifications'
