// user
export const SAVES_USER = 'SAVES_USER'
export const AUTHENTICATE = 'AUTHENTICATE'
export const UNAUTHENTICATE = 'UNAUTHENTICATE'
export const UPDATE_AUTHENTICATION = 'UPDATE_AUTHENTICATION'

// trwip
export const UPDATE_FINDED_TRWIPS = 'UPDATE_FINDED_TRWIPS'
export const CLEAN_FINDEDS = 'CLEAN_FINDEDS'

// channel
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'
export const UPDATE_CHANNELS_COUNT = 'UPDATE_CHANNELS_COUNT'
export const UPDATE_MESSAGES_COUNT = 'UPDATE_MESSAGES_COUNT'

// notification
export const SET_NOTIFICATION_AS_READ = 'SET_NOTIFICATION_AS_READ'
export const UPSERT_NOTIFICATIONS = 'UPSERT_NOTIFICATIONS'
